project:
  type: website
  output-dir: docs
  
website:
  title: "Tasnim Rida"
  site-url: "https://tasnimrida.github.io/www/"
  navbar:
    logo: assets/logo.png
    title: "Tasnim Rida"
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
    right:
      - text: Resume
        href: assets/resume.pdf
      - icon: linkedin
        href: www.linkedin.com/in/tasnim-rida
      - icon: envelope
        href: mailto:ridatasnim@gmail.com

format:
  html:
    theme: cosmo
    css: styles.css